### ISSUE TITLE
How to use this for Custom Dataset?

### ISSUE THREAD

**Issue by karndeepsingh** [Deepayan137/Adapting-OCR#11]
Hi,
I would like to use your work on my dataset. Please, guide me how can prepare my dataset so that I can use this algo over it. 
I have receipt dataset amounts and product name is hand written over it. How should I prepare my data to get these handwritten extracted. Your suggestions would help.

Thanks.

**Comment by Lotemn102** [comment]
I'd be glad to get some instructions as well. What is the expected dataset format?

**Comment by Deepayan137** [comment]
You will have to write your own data loader.
