### ISSUE TITLE
how can I use this CTC code for predicting sentences instead of words?

### ISSUE THREAD

**Issue by anidiatm41** [Deepayan137/Adapting-OCR#15]
how can I use this CTC code for predicting sentences instead of words?
we have sentences of 12 words in a crop /

**Comment by Deepayan137** [comment]
CTC does not differentiate between words or sentences. It will predict a
certain character at each time step. If your input is at sentence level and
targets are also sentences, then it will learn to predict sentences instead
of words.

**Comment by anidiatm41** [comment]
Understood Deepayan.
But somehow I found ,the CTC loss is not able to predict correctly beyond
first 10-12 characters when using sentences.

**Comment by Deepayan137** [comment]
What dataset did you use to train the model? From what I have observed, If
your dataset contains ample examples of image-text pairs, the model will
learn to predict sentences with sufficient accuracy.
